project:
  type: website
  output-dir: docs

website:
  title: "Pinkney's Sufficient Stats"
  comments:
    giscus:
      repo: spinkney/spinkney.github.io
      mapping: pathname
      reactions-enabled: true
      input-position: top
      loading: lazy
      theme: light
  navbar:
    left:
      - href: index.qmd
        text: Home
    right:
      - about.qmd
      - icon: github
        href: https://github.com/spinkney
      - icon: linkedin
        href: https://www.linkedin.com/in/sean-pinkney123/
format:
  html:
    theme: [litera, styles.scss]
    highlight-style: my-light.theme
    syntax-definitions:
      - stan.xml
    mainfont: "Atkinson Hyperlegible"
    grid:
      body-width: 1000px
      margin-width: 200px
editor: visual

# Change the background to a different color.
# Add another hyperlink in the navigation bar.
# Add your name to the left side of the top navigation bar.

# Change to another Bootswatch theme.
# Add a dark theme with another Bootswatch theme.
# Change the syntax highlighting to `eiffel`.
